"""extend_resources_and_add_resource_completions

Revision ID: 7278f0014421
Revises: 84581d0e49ea
Create Date: 2026-09-28 12:36:30.051337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7278f0014421'
down_revision: Union[str, Sequence[str], None] = '84581d0e49ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_completions',
    sa.Column('enrollment_id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('progress_seconds', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enrollment_id', 'resource_id', name='uq_enrollment_resource_completion')
    )
    op.create_index(op.f('ix_resource_completions_enrollment_id'), 'resource_completions', ['enrollment_id'], unique=False)
    op.create_index(op.f('ix_resource_completions_resource_id'), 'resource_completions', ['resource_id'], unique=False)
    op.add_column('resources', sa.Column('module_id', sa.UUID(), nullable=True))
    op.add_column('resources', sa.Column('thumbnail_url', sa.String(length=500), nullable=True))
    op.add_column('resources', sa.Column('duration_seconds', sa.Integer(), nullable=True))
    op.add_column('resources', sa.Column('display_order', sa.Integer(), server_default='0', nullable=False))
    op.add_column('resources', sa.Column('is_published', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('resources', sa.Column('created_by', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_resources_module_id'), 'resources', ['module_id'], unique=False)
    op.create_foreign_key('fk_resources_module_id', 'resources', 'course_modules', ['module_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_resources_created_by', 'resources', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_resources_created_by', 'resources', type_='foreignkey')
    op.drop_constraint('fk_resources_module_id', 'resources', type_='foreignkey')
    op.drop_index(op.f('ix_resources_module_id'), table_name='resources')
    op.drop_column('resources', 'created_by')
    op.drop_column('resources', 'is_published')
    op.drop_column('resources', 'display_order')
    op.drop_column('resources', 'duration_seconds')
    op.drop_column('resources', 'thumbnail_url')
    op.drop_column('resources', 'module_id')
    op.drop_index(op.f('ix_resource_completions_resource_id'), table_name='resource_completions')
    op.drop_index(op.f('ix_resource_completions_enrollment_id'), table_name='resource_completions')
    op.drop_table('resource_completions')
    # ### end Alembic commands ###
